"""
PDF generation utility for Shoukat Sons Garments POS reports.

Uses fpdf2 to generate professional PDF reports with headers,
footers, tables, and embedded charts.
"""

import os
import tempfile
from datetime import datetime, timezone
from typing import Dict, List, Optional

from fpdf import FPDF


class ReportPDF(FPDF):
    """
    Custom PDF class for generating business reports.

    Provides standardized headers, footers, table formatting,
    and chart embedding for all report types.
    """

    def __init__(
        self, shop_info: Dict[str, str], report_title: str
    ) -> None:
        """
        Initialize the PDF generator.

        Args:
            shop_info: Dictionary with shop name, address, phone.
            report_title: Title of the report.
        """
        assert shop_info is not None
        assert isinstance(report_title, str) and len(report_title) > 0

        super().__init__()
        self.shop_info = shop_info
        self.report_title = report_title
        self.generation_time = datetime.now(timezone.utc).strftime(
            "%Y-%m-%d %H:%M:%S"
        )

    def header(self) -> None:
        """
        Add header with shop logo, name, address, and report title.
        """
        # Shop name (left)
        self.set_font("Arial", "B", 14)
        shop_name = self.shop_info.get("name", "Shoukat Sons Garments")
        self.cell(0, 10, shop_name, 0, 1, "L")

        # Shop address (left, smaller)
        self.set_font("Arial", "", 9)
        address = self.shop_info.get("address", "")
        if address:
            self.cell(0, 5, address, 0, 1, "L")

        phone = self.shop_info.get("phone", "")
        if phone:
            self.cell(0, 5, f"Phone: {phone}", 0, 1, "L")

        # Line separator
        self.ln(3)
        self.set_draw_color(200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

        # Report title (centered)
        self.set_font("Arial", "B", 12)
        self.cell(0, 8, self.report_title, 0, 1, "C")
        self.ln(5)

    def footer(self) -> None:
        """
        Add footer with page number and generation timestamp.
        """
        # Position at 1.5 cm from bottom
        self.set_y(-15)

        self.set_font("Arial", "I", 8)
        self.set_text_color(128)

        # Page number
        page_str = f"Page {self.page_no()}/{{nb}}"
        self.cell(0, 5, page_str, 0, 0, "L")

        # Generation timestamp (right)
        self.cell(
            0,
            5,
            f"Generated by Shoukat POS - {self.generation_time}",
            0,
            0,
            "R",
        )

    def add_table(
        self,
        headers: List[str],
        rows: List[List],
        col_widths: Optional[List[int]] = None,
    ) -> None:
        """
        Add a formatted table with headers and alternating row colors.

        Args:
            headers: List of column header strings.
            rows: List of row data (each row is a list of values).
            col_widths: Optional list of column widths in mm.
        """
        assert headers is not None and len(headers) > 0
        assert rows is not None

        num_cols = len(headers)
        if col_widths is None:
            # Equal width columns
            page_width = self.w - 20  # 10mm margins on each side
            col_width = page_width / num_cols
            col_widths = [col_width] * num_cols

        # Header row
        self.set_fill_color(220, 220, 220)
        self.set_font("Arial", "B", 9)

        for i, header in enumerate(headers):
            self.cell(col_widths[i], 7, header, 1, 0, "C", True)
        self.ln()

        # Data rows with alternating colors
        self.set_font("Arial", "", 8)
        for i, row in enumerate(rows):
            # Alternating row colors
            if i % 2 == 0:
                self.set_fill_color(245, 245, 245)
            else:
                self.set_fill_color(255, 255, 255)

            for j, value in enumerate(row):
                # Convert value to string and truncate if needed
                cell_text = str(value) if value is not None else ""
                if len(cell_text) > 25:
                    cell_text = cell_text[:22] + "..."

                align = "R" if isinstance(value, (int, float)) else "L"
                self.cell(col_widths[j], 6, cell_text, 1, 0, align, True)
            self.ln()

    def add_summary_text(self, text: str, bold: bool = False) -> None:
        """
        Add a line of summary text.

        Args:
            text: Text to display.
            bold: Whether to use bold font.
        """
        assert isinstance(text, str)

        font_style = "B" if bold else ""
        self.set_font("Arial", font_style, 9)
        self.cell(0, 6, text, 0, 1, "L")
        self.ln(1)

    def add_chart(self, chart_image_path: str, width: int = 180) -> None:
        """
        Embed a chart image (PNG) in the PDF.

        Args:
            chart_image_path: Path to the PNG image file.
            width: Width of the image in mm.
        """
        assert isinstance(chart_image_path, str)
        assert os.path.exists(chart_image_path)
        assert isinstance(width, int) and width > 0

        # Calculate height to maintain aspect ratio
        try:
            img_info = self.image(chart_image_path)
        except Exception:
            # If image can't be loaded, skip it
            self.add_summary_text(f"[Chart: {chart_image_path}]")
            return

        # Center the image
        page_width = self.w - 20  # Margins
        x_pos = (page_width - width) / 2 + 10

        self.image(chart_image_path, x=x_pos, w=width)
        self.ln(5)

    def add_section_title(self, title: str) -> None:
        """
        Add a section title with spacing.

        Args:
            title: Section title text.
        """
        assert isinstance(title, str)

        self.ln(5)
        self.set_font("Arial", "B", 11)
        self.set_fill_color(230, 230, 230)
        self.cell(0, 8, title, 0, 1, "L", True)
        self.ln(2)


def generate_report_pdf(
    shop_info: Dict[str, str],
    report_title: str,
    summary_data: Optional[Dict] = None,
    table_headers: Optional[List[str]] = None,
    table_rows: Optional[List[List]] = None,
    chart_paths: Optional[List[str]] = None,
    output_dir: str = "reports",
) -> str:
    """
    Generate a complete PDF report.

    Args:
        shop_info: Dictionary with shop name, address, phone.
        report_title: Title of the report.
        summary_data: Optional dictionary of summary key-value pairs.
        table_headers: Optional list of table column headers.
        table_rows: Optional list of table row data.
        chart_paths: Optional list of paths to chart images.
        output_dir: Directory to save the PDF.

    Returns:
        Full path to the generated PDF file.
    """
    assert shop_info is not None
    assert isinstance(report_title, str) and len(report_title) > 0

    # Create output directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)

    # Generate filename with timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_title = "".join(
        c for c in report_title.replace(" ", "_") if c.isalnum() or c == "_"
    )
    filename = f"{safe_title}_{timestamp}.pdf"
    filepath = os.path.join(output_dir, filename)

    # Create PDF
    pdf = ReportPDF(shop_info, report_title)
    pdf.alias_nb_pages()
    pdf.add_page()

    # Add summary data if provided
    if summary_data:
        pdf.add_section_title("Summary")
        for key, value in summary_data.items():
            if isinstance(value, (int, float)):
                # Format as currency (cents to rupees)
                rupees = value / 100
                text = f"{key}: Rs. {rupees:,.2f}"
            else:
                text = f"{key}: {value}"
            pdf.add_summary_text(text)
        pdf.ln(5)

    # Add table if provided
    if table_headers and table_rows:
        pdf.add_section_title("Details")
        pdf.add_table(table_headers, table_rows)

    # Add charts if provided
    if chart_paths:
        pdf.add_section_title("Charts")
        for chart_path in chart_paths:
            if os.path.exists(chart_path):
                pdf.add_chart(chart_path)
                pdf.ln(5)

    # Save PDF
    pdf.output(filepath)

    return filepath


def format_currency(cents: int) -> str:
    """
    Format cents as Pakistani Rupees string.

    Args:
        cents: Amount in cents.

    Returns:
        Formatted string like "Rs. 1,250.00".
    """
    assert isinstance(cents, int)
    rupees = cents / 100
    return f"Rs. {rupees:,.2f}"
